This File will take the 2022 data and create the

In [1]:
import pandas as pd 
import numpy as np
import os

In [2]:
#Use this file path for pc
filepath = r"D:\gradschool\Capstone"
#Use this file path for mac 
#filepath = r"/Users/jacksonjoyner/Desktop/MSBA/Capstone/UseThisData/"
os.chdir(filepath)

In [3]:
matchdf = pd.read_csv("2022_LoL_esports_match.csv")
matchdf

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,ESPORTSTMNT01_2690210,complete,NaN,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,...,121.0,391.0,345.0,14.0,0.0,1.0,0.0,0.0,1.0,0.0
1,ESPORTSTMNT01_2690210,complete,NaN,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,...,100.0,541.0,-275.0,-11.0,2.0,3.0,2.0,0.0,5.0,1.0
2,ESPORTSTMNT01_2690210,complete,NaN,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,...,119.0,-475.0,153.0,1.0,0.0,3.0,0.0,3.0,3.0,2.0
3,ESPORTSTMNT01_2690210,complete,NaN,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,...,149.0,-793.0,-1343.0,-34.0,2.0,1.0,2.0,3.0,3.0,0.0
4,ESPORTSTMNT01_2690210,complete,NaN,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,...,21.0,443.0,-497.0,7.0,1.0,2.0,2.0,0.0,6.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61171,ESPORTSTMNT01_2862480,complete,NaN,LCS,2022,NaN,1,2022-04-24 21:14:20,3,12.06,...,129.0,340.0,351.0,29.0,1.0,0.0,1.0,2.0,0.0,0.0
61172,ESPORTSTMNT01_2862480,complete,NaN,LCS,2022,NaN,1,2022-04-24 21:14:20,3,12.06,...,137.0,217.0,260.0,6.0,0.0,3.0,1.0,3.0,1.0,2.0
61173,ESPORTSTMNT01_2862480,complete,NaN,LCS,2022,NaN,1,2022-04-24 21:14:20,3,12.06,...,22.0,663.0,198.0,0.0,2.0,1.0,2.0,0.0,3.0,1.0
61174,ESPORTSTMNT01_2862480,complete,NaN,LCS,2022,NaN,1,2022-04-24 21:14:20,3,12.06,...,560.0,-2087.0,-1242.0,-55.0,5.0,7.0,4.0,4.0,5.0,5.0
61175,ESPORTSTMNT01_2862480,complete,NaN,LCS,2022,NaN,1,2022-04-24 21:14:20,3,12.06,...,505.0,2087.0,1242.0,55.0,4.0,5.0,5.0,5.0,7.0,4.0

In [4]:
listid = matchdf['gameid'].tolist()
setid = set(listid)
playerdf = pd.DataFrame()
for item in setid:
    df_new = matchdf[matchdf["gameid"]== item]
    player = df_new.iloc[:10]
    playerdf = playerdf.append(player)

In [5]:
playerdf

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
3684,ESPORTSTMNT01_2693060,complete,NaN,LPLOL,2022,Spring,0,2022-01-17 22:56:00,1,12.01,...,129.0,-1611.0,-1501.0,-26.0,0.0,0.0,2.0,1.0,1.0,0.0
3685,ESPORTSTMNT01_2693060,complete,NaN,LPLOL,2022,Spring,0,2022-01-17 22:56:00,1,12.01,...,86.0,1514.0,874.0,11.0,1.0,1.0,0.0,0.0,1.0,1.0
3686,ESPORTSTMNT01_2693060,complete,NaN,LPLOL,2022,Spring,0,2022-01-17 22:56:00,1,12.01,...,99.0,1390.0,23.0,12.0,1.0,2.0,1.0,0.0,1.0,2.0
3687,ESPORTSTMNT01_2693060,complete,NaN,LPLOL,2022,Spring,0,2022-01-17 22:56:00,1,12.01,...,143.0,-1733.0,-214.0,-23.0,0.0,0.0,0.0,2.0,0.0,0.0
3688,ESPORTSTMNT01_2693060,complete,NaN,LPLOL,2022,Spring,0,2022-01-17 22:56:00,1,12.01,...,6.0,-728.0,-1235.0,14.0,1.0,0.0,1.0,1.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26405,ESPORTSTMNT03_2548427,complete,NaN,NLC,2022,Spring,0,2022-02-21 19:23:48,1,12.03,...,125.0,3021.0,2469.0,40.0,3.0,0.0,1.0,0.0,1.0,3.0
26406,ESPORTSTMNT03_2548427,complete,NaN,NLC,2022,Spring,0,2022-02-21 19:23:48,1,12.03,...,63.0,1837.0,632.0,34.0,2.0,2.0,1.0,0.0,2.0,1.0
26407,ESPORTSTMNT03_2548427,complete,NaN,NLC,2022,Spring,0,2022-02-21 19:23:48,1,12.03,...,120.0,2512.0,1281.0,25.0,2.0,3.0,0.0,0.0,0.0,2.0
26408,ESPORTSTMNT03_2548427,complete,NaN,NLC,2022,Spring,0,2022-02-21 19:23:48,1,12.03,...,121.0,-335.0,-67.0,4.0,1.0,2.0,1.0,4.0,0.0,0.0
26409,ESPORTSTMNT03_2548427,complete,NaN,NLC,2022,Spring,0,2022-02-21 19:23:48,1,12.03,...,24.0,-820.0,-560.0,-3.0,0.0,3.0,2.0,1.0,4.0,2.0

There are a number of columns that contain little to no data, so we are just going to remove them from the df. We would keep them if we were looking at team specific data.

In [6]:
playerdf = playerdf.drop(["firstdragon", 'dragons','opp_dragons','elementaldrakes','opp_elementaldrakes','infernals','mountains','clouds','oceans','dragons (type unknown)','elders','opp_elders','firstherald','heralds','opp_heralds','firstbaron','barons','opp_barons','firsttower','towers','opp_towers','firstmidtower','firsttothreetowers','turretplates','opp_turretplates','inhibitors','opp_inhibitors'], axis = 1)

Now that the data is cleaned up, lets separate it by region, and only take the region we want to test on. In this case,

In [7]:
leagueset = list(playerdf["league"])
leagueset = set(leagueset)
mainregions = pd.DataFrame()
league = ['LCS']
for item in league:
    throwaway = playerdf[playerdf["league"] == item]
    mainregions = mainregions.append(throwaway)

In [8]:
mainregions

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
10092,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,130.0,-1018.0,-144.0,-24.0,2.0,0.0,1.0,1.0,0.0,2.0
10093,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,106.0,-314.0,125.0,-19.0,1.0,7.0,0.0,0.0,1.0,1.0
10094,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,137.0,1475.0,531.0,9.0,3.0,3.0,0.0,0.0,0.0,1.0
10095,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,112.0,1693.0,598.0,25.0,3.0,2.0,1.0,0.0,1.0,2.0
10096,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,18.0,472.0,544.0,-12.0,0.0,7.0,0.0,1.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2885,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,128.0,-1562.0,0.0,-35.0,0.0,2.0,2.0,1.0,1.0,1.0
2886,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,88.0,-440.0,627.0,6.0,1.0,3.0,0.0,1.0,1.0,1.0
2887,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,144.0,331.0,336.0,7.0,2.0,1.0,0.0,0.0,1.0,1.0
2888,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,120.0,1066.0,943.0,29.0,0.0,1.0,0.0,0.0,0.0,0.0
2889,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,24.0,797.0,56.0,-19.0,1.0,0.0,0.0,0.0,0.0,1.0

Lets add the new metrics to this dataset

In [9]:
mainregions["KDA"] = (mainregions["kills"]+mainregions["assists"]) / mainregions["deaths"]
mainregions["KP"] = (mainregions["kills"]+mainregions["assists"])  / mainregions["teamkills"]
mainregions["D%"] = mainregions["deaths"] / mainregions['teamdeaths']
mainregions["FantasyScore"] = (mainregions['kills']*3)-mainregions["deaths"]+(mainregions['assists']*1.5)+(mainregions["total cs"]*.02)
mainregions

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,KDA,KP,D%,FantasyScore
10092,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,2.0,0.0,1.0,1.0,0.0,2.0,1.333333,0.307692,0.187500,10.58
10093,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,1.0,7.0,0.0,0.0,1.0,1.0,3.333333,0.769231,0.187500,16.90
10094,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,3.0,3.0,0.0,0.0,0.0,1.0,2.000000,0.615385,0.250000,18.92
10095,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,3.0,2.0,1.0,0.0,1.0,2.0,3.000000,0.692308,0.187500,28.42
10096,ESPORTSTMNT02_2571892,complete,NaN,LCS,2022,Spring,1,2022-01-29 00:17:44,3,12.02,...,0.0,7.0,0.0,1.0,0.0,3.0,3.666667,0.846154,0.187500,14.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2885,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,0.0,2.0,2.0,1.0,1.0,1.0,2.400000,0.631579,0.384615,23.02
2886,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,1.0,3.0,0.0,1.0,1.0,1.0,7.500000,0.789474,0.153846,29.88
2887,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,2.0,1.0,0.0,0.0,1.0,1.0,7.500000,0.789474,0.153846,33.92
2888,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,0.0,1.0,0.0,0.0,0.0,0.0,5.500000,0.578947,0.153846,29.44
2889,ESPORTSTMNT01_2702196,complete,NaN,LCS,2022,Spring,1,2022-01-16 00:14:51,1,12.01,...,1.0,0.0,0.0,0.0,0.0,1.0,6.000000,0.631579,0.153846,18.06

Time to reduce the datset even more. There are alot of variables not usefull for the analysis, so removing the variables is best for efficiency

In [11]:
variables = ['league','year','split','date','side',"playername",'position','teamname',"kills","deaths",'assists','doublekills','firstbloodkill'
             ,'firstbloodassist','firstbloodvictim','dpm','wpm','goldspent','total cs','minionkills','monsterkills',
             'monsterkillsenemyjungle','goldat15','xpat15','csat15','golddiffat15','xpdiffat15',
             'csdiffat15','killsat15','deathsat15','assistsat15','result','FantasyScore','KDA','KP','D%',"earnedgoldshare",
            'damageshare','cspm','damagetakenperminute','earnedgold','earned gpm']
#the commented section is if you are finding a null error in the factor reduction. In my case, the LCS 
#data doesn't have those issues, so I keep it commented out
reduced_df = mainregions[variables]#[mainregions["datacompleteness"]== 'complete'].dropna(how="any")
#reduced_df.to_csv("2022_Reduced.csv", index = False)

Now we can reduce the variables that we know have collinearity issues

In [12]:
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [13]:
#The first variable will be the @15 minute variables
features15 = ['goldat15','xpat15','csat15']
x = reduced_df.loc[:,features15].values
y = reduced_df.loc[:,['playername']].values
x = StandardScaler().fit_transform(x)
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x)
reduced_df['PCA15'] = principalComponents
pca.explained_variance_ratio_

<ipython-input-13-7360c4edab27>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_df['PCA15'] = principalComponents

array([0.87632356])

In [14]:
featureshare = ["earnedgoldshare",'damageshare']
x = reduced_df.loc[:,featureshare].values
y = reduced_df.loc[:,['playername']].values
x = StandardScaler().fit_transform(x)
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x)
reduced_df['PCAShare'] = principalComponents
pca.explained_variance_ratio_

<ipython-input-14-e2d36bac2fac>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_df['PCAShare'] = principalComponents

array([0.90961848])

In [15]:
featureshare= ['earned gpm','cspm']
x = reduced_df.loc[:,featureshare].values
y = reduced_df.loc[:,["playername"]].values
x = StandardScaler().fit_transform(x)
#n_components should equal the total amount of components at the end
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(x)
reduced_df["PCApm"] = principalComponents
pca.explained_variance_ratio_

<ipython-input-15-d809638392b2>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_df["PCApm"] = principalComponents

array([0.93571833])

In [36]:
reduced_df['Counts'] = reduced_df.groupby(['playername'])['playername'].transform("count")
reduced_df
reduced_df.to_csv("2022_Reduced.csv", index = False)

<ipython-input-36-bd97fb2c2606>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_df['Counts'] = reduced_df.groupby(['playername'])['playername'].transform("count")

Now that we have the reduced variables, we can test the data in the model created in a previous file. 
This code and old file will be brought in.

In [17]:
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.graphics.gofplots import ProbPlot
plt.style.use('seaborn') # pretty matplotlib plots
plt.rc('font', size=14)
plt.rc('figure', titlesize=18)
plt.rc('axes', labelsize=15)

In [18]:
playerdf = pd.read_csv("PCATest1.csv")
playerdf = playerdf.rename(columns ={"total cs" : "total_cs"})#the statsmodel doesn't allow for spaces in variable names

In [19]:
variables = ['kills','deaths','assists','PCA15','PCAShare','PCApm']
x = playerdf[variables].to_numpy() 
y = playerdf["result"]

In [20]:
model = sm.Logit(y, sm.add_constant(x)).fit()
Y_pred = model.predict(sm.add_constant(x))
print_model = model.summary()
print(print_model)

Optimization terminated successfully.
         Current function value: 0.245784
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                 result   No. Observations:                92600
Model:                          Logit   Df Residuals:                    92593
Method:                           MLE   Df Model:                            6
Date:                Mon, 25 Apr 2022   Pseudo R-squ.:                  0.6454
Time:                        15:35:40   Log-Likelihood:                -22760.
converged:                       True   LL-Null:                       -64185.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7205      0.031    -55.765      0.000      -1.781      -1.660
x1             0.4857      0.007     65.458      0.000       0.471       0.500
x2            -0.8946      0.009    -99.537      0.000      -0.912      -0.877
x3             0.4696      0.004    108.081      0.000       0.461       0.478
x4            -0.5684      0.017    -33.800      0.000      -0.601      -0.535
x5            -2.3178      0.026    -88.354      0.000      -2.369      -2.266
x6             2.8647      0.033     87.123      0.000       2.800       2.929
==============================================================================

Now that we have the original model, lets fit our 2022 data to this model

In [21]:
variables = ['kills','deaths','assists','PCA15','PCAShare','PCApm'] # Sets X variables
x = reduced_df[variables].to_numpy() #makes the x variables an array, needed for the model
y = reduced_df["result"] # y variable

In [23]:
red_model = sm.Logit(y, sm.add_constant(x)).fit() #Creates model
Y_pred = red_model.predict(sm.add_constant(x)) #produces predictions
print_model = red_model.summary() #creates the summary table
reduced_df['predscore'] = Y_pred # adds predictions to df
print(print_model)

Optimization terminated successfully.
         Current function value: 0.240386
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                 result   No. Observations:                 1600
Model:                          Logit   Df Residuals:                     1593
Method:                           MLE   Df Model:                            6
Date:                Mon, 25 Apr 2022   Pseudo R-squ.:                  0.6532
Time:                        15:35:46   Log-Likelihood:                -384.62
converged:                       True   LL-Null:                       -1109.0
Covariance Type:            nonrobust   LLR p-value:                6.446e-310
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.8350      0.250     -7.343      0.000      -2.325      -1.345
x1             0.4864      0.062      7.787      0.000       0.364       0.609
x2            -0.9840      0.075    -13.177      0.000      -1.130      -0.838
x3             0.5625      0.037     15.111      0.000       0.490       0.635
x4             0.5369      0.140      3.838      0.000       0.263       0.811
x5            -2.0661      0.208     -9.952      0.000      -2.473      -1.659
x6             2.6703      0.282      9.458      0.000       2.117       3.224
==============================================================================

<ipython-input-23-229d7f77e9ce>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_df['predscore'] = Y_pred

Now that We have this new 2022 model, we can see the rank the teams based on the predicted scores

In [46]:
predict_df = reduced_df.groupby('teamname', as_index = False)['predscore'].mean()
predict_df.sort_values(by=['predscore'])

               teamname  predscore
7             Immortals   0.315123
2  Counter Logic Gaming   0.348390
8                   TSM   0.356633
6      Golden Guardians   0.378550
5              FlyQuest   0.396684
3              Dignitas   0.447762
1                Cloud9   0.560809
0           100 Thieves   0.590080
4         Evil Geniuses   0.635076
9           Team Liquid   0.658021

We can do the same with players, and the player with the highest average score would be MVP

In [45]:
#We need to drop players that played less than the half of the games in the regular season.
#This is how Riot Games 
mvp = reduced_df.groupby('Counts').filter(lambda x: len(x)>9)

mvp_df = mvp.groupby('playername',as_index = False)['predscore'].mean()
mvp_df.sort_values(by=['predscore'])
#mvp_df.to_csv("2022_MVP.csv",index = False)

   playername  predscore
53      V1per   0.079778
58     Yursan   0.178802
52   Tony Top   0.182977
63      ry0ma   0.187113
9       Chime   0.187478
..        ...        ...
20  Hans sama   0.677710
13      Danny   0.681534
44   Santorin   0.732451
25   Inspired   0.743803
5    Bjergsen   0.748510

[65 rows x 2 columns]

According to this model, Bjergsen should have been the Spring Split MVP, if you include playoff games. Typically MVP is based only on regular season, but I like the regular + post season MVP discussion better.

This section is getting important info from the model for the writting of the paper

In [52]:
params = red_model.params
exp = np.exp(params)
exp

const     0.159610
x1        1.626441
x2        0.373817
x3        1.755004
x4        1.710729
x5        0.126673
x6       14.444928
dtype: float64

In [54]:
conf = red_model.conf_int()
conf = np.exp(conf)
conf

              0          1
const  0.097802   0.260479
x1     1.439041   1.838244
x2     0.322919   0.432736
x3     1.631529   1.887824
x4     1.300516   2.250332
x5     0.084328   0.190281
x6     8.305868  25.121512