In [1]:
import pandas as pd
import numpy as np
import os

We are going to be opening the match data files and splitting the rows into two different files. One is all of the player data, the other is all of the team data

In [19]:
#I have my data stored in a different location from this file, so I need to change my working directory.
#If your data is in the same location as this file, ignore this line
#making the actual filepath a variable is an important step that we will use later in the code. DO NOT FORGET IT

filepath = 'D:\gradschool\Capstone\Data\Match_Data'
os.chdir(filepath)

Now that we have our data location, we can pull in a csv and start tinkering with it.

These Match Data csv files are a bit wonky. For each game, there are 12 lines of data, 10 rows of player data and two rows of team data. There are columns not being used by players, but are for teams. So this is where we are going to clean the data up and split it into two different files.

This section is just to make sure its done correctly before we throw it into a loop to do with all of the data.

In [31]:
test = pd.read_csv("2014_LoL_esports_match_data.csv")
test

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,111,49,-560,-1,2,0,0,1,1,1
1,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,95,-1107,-703,-36,0,2,2,2,0,0
2,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,126,-145,-148,7,0,1,1,0,2,0
3,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,103,1588,998,22,3,0,0,0,0,3
4,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,23,887,476,-15,0,4,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11011,FRA1TMNT1/430152,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2015,Spring,0,2014-12-21 14:23:43,3,4.21,...,128,687,1428,15,2,1,0,0,1,0
11012,FRA1TMNT1/430152,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2015,Spring,0,2014-12-21 14:23:43,3,4.21,...,115,1143,825,30,2,0,0,0,0,2
11013,FRA1TMNT1/430152,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2015,Spring,0,2014-12-21 14:23:43,3,4.21,...,18,-266,-291,-15,0,1,0,1,0,0
11014,FRA1TMNT1/430152,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2015,Spring,0,2014-12-21 14:23:43,3,4.21,...,435,-2167,-918,-33,2,2,6,6,7,2
11015,FRA1TMNT1/430152,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2015,Spring,0,2014-12-21 14:23:43,3,4.21,...,402,2167,918,33,6,7,2,2,2,6

In [4]:
#We are going to make a set of gameid's so we can split the data accordingly

listid = test["gameid"].tolist()
setid = set(listid)

Now that we have a set of gameid's, we can now pull single game data

In [13]:
df_new = test[test['gameid'] == 'TRLH3/33']
df_last2 = df_new.iloc[-2:]
df_top10 = df_new.iloc[:10]

In [18]:
players = pd.DataFrame()
players = players.append(df_top10)
players

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,111,49,-560,-1,2,0,0,1,1,1
1,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,95,-1107,-703,-36,0,2,2,2,0,0
2,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,126,-145,-148,7,0,1,1,0,2,0
3,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,103,1588,998,22,3,0,0,0,0,3
4,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,23,887,476,-15,0,4,0,0,0,1
5,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,110,-49,560,1,1,1,1,2,0,0
6,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,59,1107,703,36,2,0,0,0,2,2
7,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,133,145,148,-7,0,2,0,0,1,1
8,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,125,-1588,-998,-22,0,0,3,3,0,0
9,TRLH3/33,complete,http://matchhistory.na.leagueoflegends.com/en/...,EU LCS,2014,Spring,0,2014-01-14 17:52:02,1,3.15,...,8,-887,-476,15,0,0,1,0,4,0

Now that we know how to get player data and team data seperated, we can run the loop to do this automatically.

In [20]:
#The first step is getting all of our data files loaded in
files = []
location = os.listdir(filepath)
for item in location:
    files.append(item)

In [35]:
counter = 2014
for file in files:
    fulldata = pd.read_csv(file)
    listid = fulldata["gameid"].tolist()
    setid = set(listid)
    player_data = pd.DataFrame()
    team_data = pd.DataFrame()
    for item in setid:
        df_new = fulldata[fulldata['gameid'] == item]
        team = df_new.iloc[-2:]
        player = df_new.iloc[:10]
        player_data = player_data.append(player)
        team_data = team_data.append(team)
    print("")
    player_data.to_csv(str(counter)+"_player_data.csv",index = False)
    print("Player Data CSV Created")
    team_data.to_csv(str(counter)+"_team_data.csv",index = False)
    print("Team Data CSV Created")
    counter += 1

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created

Player Data CSV Created
Team Data CSV Created